str='   DATA Engineer    '

print(str.capitalize())
print(str.title())
print(str.upper())
print(str.lower())
print(str.swapcase())
print(str.center(25,'*'))
print(str.split())
print(str.lstrip())
print(str.rstrip())
print(str.strip())
print(str.casefold())
print(str.count('A'))
print(str.replace('Engineer','Scientist'))